from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(packagebook)
admin.site.register(flight)
admin.site.register(Packages)
admin.site.register(train)
admin.site.register(bus)
admin.site.register(hotel)
admin.site.register(cab)
admin.site.register(FlightClass)
admin.site.register(contact)
admin.site.register(Vehicles)
admin.site.register(services)
admin.site.register(flythrough)
admin.site.register(TarinClass)
admin.site.register(busClass)
admin.site.register(FlightCities)
admin.site.register(ToFlightCities)
admin.site.register(hotelproperty)
admin.site.register(FromTrcity)
admin.site.register(ToTrcity)
admin.site.register(FromBuscity)
admin.site.register(ToBuscity)
admin.site.register(FromCabcity)
admin.site.register(ToCabcity)
admin.site.register(CabPrice)
admin.site.register(Airlines)