# Generated by Django 4.2 on 2023-05-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='packagebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=50, unique=True)),
                ('package_mobNo', models.CharField(max_length=10, unique=True)),
                ('package_guestmember', models.IntegerField()),
                ('package_leaving', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
