# Generated by Django 4.2 on 2023-05-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebook',
            name='package_leaving',
            field=models.DateField(),
        ),
    ]
