# Generated by Django 4.2 on 2023-05-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_packagebook_package_leaving'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50, unique=True)),
                ('book_mobNo', models.CharField(max_length=10, unique=True)),
                ('book_location', models.CharField(max_length=50)),
                ('book_guestmember', models.IntegerField()),
                ('book_leaving', models.DateField()),
            ],
        ),
    ]
