# Generated by Django 4.2 on 2023-06-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_remove_packagebook_package_guestmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_fromd', models.CharField(max_length=50)),
                ('flight_tod', models.CharField(max_length=50)),
                ('flight_date', models.DateField(auto_now_add=True)),
                ('flight_time', models.TimeField(auto_now_add=True)),
                ('flight_airline', models.CharField(max_length=50)),
                ('flight_seat', models.CharField(max_length=50)),
                ('flight_adult', models.IntegerField()),
                ('flight_Children', models.IntegerField()),
                ('flight_infant', models.IntegerField()),
                ('flight_trip', models.CharField(max_length=50)),
                ('flight_redate', models.DateField(auto_now_add=True)),
                ('flight_retime', models.TimeField(auto_now_add=True)),
                ('flight_anymessage', models.CharField(max_length=50)),
                ('flight_fname', models.CharField(max_length=50)),
                ('flight_mobNo', models.CharField(max_length=10, unique=True)),
                ('flight_email', models.EmailField(max_length=254)),
                ('flight_identitytype', models.CharField(max_length=50)),
                ('flight_identityno', models.CharField(max_length=50)),
            ],
        ),
    ]
