# Generated by Django 4.2.2 on 2023-06-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='train_time',
        ),
        migrations.AddField(
            model_name='train',
            name='train_trainname',
            field=models.CharField(default='basva', max_length=50),
        ),
    ]
