# Generated by Django 4.2.2 on 2023-06-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_remove_train_train_time_train_train_trainname'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebook',
            name='package_guestmember',
            field=models.IntegerField(default=1),
        ),
    ]
