# Generated by Django 4.2.2 on 2023-06-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_packagebook_package_guestmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_jfrom', models.CharField(max_length=50)),
                ('bus_jto', models.CharField(max_length=50)),
                ('bus_date', models.DateField(auto_now_add=True)),
                ('bus_bustype', models.CharField(max_length=50)),
                ('bus_passengers', models.IntegerField()),
            ],
        ),
    ]
