# Generated by Django 4.2.2 on 2023-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_packages_adventure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='packagebook',
            name='package_name',
            field=models.CharField(max_length=50),
        ),
    ]
