# Generated by Django 4.2.2 on 2023-06-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flight_date',
            new_name='flight_adate',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='flight_airline',
            new_name='flight_classs',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='flight_redate',
            new_name='flight_ddate',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_anymessage',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_infant',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_retime',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_seat',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='user_fname',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='user_identityno',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='user_identitytype',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='user_mobNo',
        ),
    ]
