# Generated by Django 4.2.2 on 2023-06-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_rename_flight_date_flight_flight_adate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='user_name',
            field=models.CharField(default='unknown user', max_length=50),
        ),
    ]
