# Generated by Django 4.2.2 on 2023-06-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_flight_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_city',
            new_name='hotel_adults',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_fname',
            new_name='hotel_childs',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_hoteltype',
            new_name='hotel_cityorproprty',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_identityno',
            new_name='hotel_price',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_identitytype',
            new_name='hotel_rooms',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_email',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_lname',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_mobNo',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_numberpdeople',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_roomtype',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_state',
        ),
    ]
