# Generated by Django 4.2.2 on 2023-06-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_rename_hotel_city_hotel_hotel_adults_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_bustype',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='bus_passengers',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='user_age',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='user_identityno',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='user_identitytype',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='user_mobNo',
        ),
    ]
