# Generated by Django 4.2.2 on 2023-06-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_remove_bus_bus_bustype_remove_bus_bus_passengers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='train_reservation',
            new_name='train_class',
        ),
        migrations.RemoveField(
            model_name='train',
            name='train_passengers',
        ),
        migrations.RemoveField(
            model_name='train',
            name='train_trainname',
        ),
        migrations.RemoveField(
            model_name='train',
            name='user_age',
        ),
        migrations.RemoveField(
            model_name='train',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='train',
            name='user_identityno',
        ),
        migrations.RemoveField(
            model_name='train',
            name='user_identitytype',
        ),
        migrations.RemoveField(
            model_name='train',
            name='user_mobNo',
        ),
        migrations.AlterField(
            model_name='train',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
