# Generated by Django 4.2.2 on 2023-06-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_rename_train_reservation_train_train_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('cab_from', models.CharField(max_length=50)),
                ('cab_to', models.CharField(max_length=50)),
                ('cab_departuredate', models.DateField(auto_now_add=True)),
                ('cab_returndate', models.DateField(auto_now_add=True)),
                ('cab_pickuptime', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
