# Generated by Django 4.2.2 on 2023-06-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_cab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='cab_departuredate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cab',
            name='cab_pickuptime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cab',
            name='cab_returndate',
            field=models.DateField(),
        ),
    ]
