# Generated by Django 4.2.2 on 2023-06-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0026_alter_vehicles_timings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_adate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_ddate',
            field=models.DateField(),
        ),
    ]
