# Generated by Django 4.2.2 on 2023-06-23 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0027_delete_book_alter_flight_flight_adate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebook',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_checkin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_checkout',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='packagebook',
            name='package_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='travel.packages'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_date',
            field=models.DateField(),
        ),
    ]
