# Generated by Django 4.2.2 on 2023-06-23 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0028_packagebook_user_alter_bus_bus_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebook',
            name='package_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.packages'),
        ),
        migrations.AlterField(
            model_name='packagebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
