# Generated by Django 4.2.2 on 2023-06-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0030_remove_packagebook_id_packagebook_package_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebook',
            name='package_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
