# Generated by Django 4.2.2 on 2023-06-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0031_alter_packagebook_package_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_number', models.CharField(max_length=50)),
                ('services_title', models.CharField(max_length=50)),
                ('services_description', models.TextField(max_length=500)),
            ],
        ),
    ]
