# Generated by Django 4.2.2 on 2023-06-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0032_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='flythrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fly_image', models.ImageField(upload_to='images')),
                ('fly_title', models.CharField(max_length=50)),
                ('fly_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='timings',
            field=models.CharField(choices=[('0', ''), ('1', 'Morning'), ('2', 'Evening'), ('3', 'Night')], default=0, max_length=50),
        ),
    ]
