# Generated by Django 4.2.2 on 2023-06-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0034_cities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cities',
        ),
    ]
