# Generated by Django 4.2.2 on 2023-06-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0036_flightclass_delete_hoteltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightclass',
            name='flight_price_currency',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='package_price_currency',
        ),
        migrations.AlterField(
            model_name='flightclass',
            name='flight_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_price',
            field=models.IntegerField(),
        ),
    ]
