# Generated by Django 4.2.2 on 2023-06-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0037_remove_flightclass_flight_price_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarinClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_class', models.CharField(max_length=50)),
                ('train_price', models.IntegerField()),
            ],
        ),
    ]
