# Generated by Django 4.2.2 on 2023-06-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0039_alter_flight_flight_classs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_classs',
            field=models.CharField(max_length=50),
        ),
    ]
