# Generated by Django 4.2.2 on 2023-06-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0040_alter_flight_flight_classs'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_amount',
            field=models.IntegerField(default=0),
        ),
    ]
