# Generated by Django 4.2.2 on 2023-06-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0041_flight_flight_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='train_amount',
            field=models.IntegerField(default=0),
        ),
    ]
