# Generated by Django 4.2.2 on 2023-06-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0042_train_train_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_adult',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_class',
            field=models.CharField(default='non AC', max_length=50),
        ),
        migrations.AddField(
            model_name='train',
            name='train_adult',
            field=models.IntegerField(default=1),
        ),
    ]
