# Generated by Django 4.2.2 on 2023-06-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0043_bus_bus_adult_bus_bus_amount_bus_bus_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='busClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_class', models.CharField(max_length=50)),
                ('bus_price', models.IntegerField()),
            ],
        ),
    ]
