# Generated by Django 4.2.2 on 2023-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0048_toflightcities'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotelproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=50)),
            ],
        ),
    ]
