# Generated by Django 4.2.2 on 2023-06-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0049_hotelproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='user_name',
            field=models.CharField(default='afnan', max_length=50),
        ),
    ]
