# Generated by Django 4.2.2 on 2023-06-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0050_hotel_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromTrcity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ToTrcity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=50)),
            ],
        ),
    ]
