# Generated by Django 4.2.2 on 2023-06-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0052_frombuscity_tobuscity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromCabcity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ToCabcity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cab',
            name='Cars_Price',
            field=models.CharField(default='SUV', max_length=50),
        ),
    ]
