# Generated by Django 4.2.2 on 2023-07-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0057_alter_packages_package_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_checkout',
            field=models.DateField(),
        ),
    ]
