# Generated by Django 4.2.2 on 2023-07-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0058_alter_hotel_hotel_checkin_alter_hotel_hotel_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='toflightcities',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
