# Generated by Django 4.2.2 on 2023-07-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0063_withflt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withflt',
            name='fromtoto',
            field=models.CharField(max_length=50),
        ),
    ]
