# Generated by Django 4.2.2 on 2023-07-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0064_alter_withflt_fromtoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Withflt',
        ),
    ]
